version: 0.2

env:
  variables:
    MAVEN_OPTS: -DskipTests
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Running SCA (OWASP Dependency-Check)"
      - mvn -q -DskipTests org.owasp:dependency-check-maven:check || true
      - echo "Running SAST (SonarQube)"
      - |
        if [ -n "$SONAR_HOST_URL" ] && [ -n "$SONAR_TOKEN" ]; then
          mvn -q -DskipTests sonar:sonar -Dsonar.projectKey=bolsas -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN || true
        else
          echo "Sonar not configured, skipping"
        fi
  build:
    commands:
      - mvn -q -DskipTests package
  post_build:
    commands:
      - echo "Running DAST with OWASP ZAP against STAGING_URL if provided"
      - |
        if [ -n "$STAGING_URL" ]; then
          docker run --rm -t zaproxy/zap-stable:latest zap-baseline.py -t $STAGING_URL -r zap-report.html || true
        else
          echo "No STAGING_URL provided, skipping ZAP"
        fi
artifacts:
  files:
    - target/*.jar
    - zap-report.html
  discard-paths: yes
